<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            
            <!-- Welcome Section -->
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <h3 class="text-lg font-semibold mb-2">Welcome back, {{ Auth::user()->name }}!</h3>
                    <p class="text-gray-600">Ready to achieve your goals today?</p>
                </div>
            </div>

            <!-- SMART Goals Video Section -->
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6">
                    <h3 class="text-lg font-semibold mb-4 text-gray-900">Learn About SMART Goals</h3>
                    <div class="bg-gray-100 rounded-lg p-4">
                        <div class="flex items-center justify-between mb-3">
                            <div>
                                <h4 class="font-medium text-gray-900">How to Set SMART Goals</h4>
                                <p class="text-sm text-gray-600">Learn the proven framework for setting achievable goals</p>
                            </div>
                            <svg class="w-12 h-12 text-blue-500" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z"/>
                            </svg>
                        </div>
                        <button onclick="showSmartGoalsVideo()" class="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md text-sm font-medium transition-colors">
                            Watch Video
                        </button>
                    </div>
                </div>
            </div>

            <!-- Goal Calendar and Quick Creation -->
            <div class="grid grid-cols-1 xl:grid-cols-3 gap-6">
                
                <!-- Calendar View -->
                <div class="xl:col-span-2 bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6">
                        <div class="flex items-center justify-between mb-4">
                            <h3 class="text-lg font-semibold text-gray-900">Goal Calendar</h3>
                            <div class="flex space-x-2">
                                <button onclick="previousMonth()" class="p-2 text-gray-400 hover:text-gray-600">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/>
                                    </svg>
                                </button>
                                <button onclick="nextMonth()" class="p-2 text-gray-400 hover:text-gray-600">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                                    </svg>
                                </button>
                            </div>
                        </div>
                        
                        <div id="calendar" class="bg-gray-50 rounded-lg p-4">
                            <!-- Calendar will be generated by JavaScript -->
                        </div>
                        
                        <div class="mt-4 text-sm text-gray-600">
                            <div class="flex items-center space-x-4">
                                <div class="flex items-center">
                                    <div class="w-3 h-3 bg-blue-100 rounded mr-2"></div>
                                    <span>Active Goals</span>
                                </div>
                                <div class="flex items-center">
                                    <div class="w-3 h-3 bg-green-100 rounded mr-2"></div>
                                    <span>Completed</span>
                                </div>
                                <div class="flex items-center">
                                    <span class="mr-2">🔄</span>
                                    <span>Recurring</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Quick Goal Creation -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6">
                        <h3 class="text-lg font-semibold mb-4 text-gray-900">Schedule a Goal</h3>
                        <form action="{{ route('goals.store') }}" method="POST" class="space-y-4">
                            @csrf
                            <div>
                                <label for="title" class="block text-sm font-medium text-gray-700 mb-1">Goal Title</label>
                                <input type="text" 
                                       id="title" 
                                       name="title" 
                                       class="w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring-blue-500" 
                                       placeholder="e.g., Run a 5K marathon"
                                       value="{{ old('title') }}"
                                       required>
                                @error('title')
                                    <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
                                @enderror
                            </div>
                            
                            <div>
                                <label for="description" class="block text-sm font-medium text-gray-700 mb-1">Description (Optional)</label>
                                <textarea id="description" 
                                          name="description" 
                                          rows="2" 
                                          class="w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring-blue-500" 
                                          placeholder="Add more details...">{{ old('description') }}</textarea>
                            </div>
                            
                            <div>
                                <label for="recurrence_type" class="block text-sm font-medium text-gray-700 mb-1">Goal Type</label>
                                <select id="recurrence_type" 
                                        name="recurrence_type" 
                                        class="w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring-blue-500"
                                        onchange="toggleRecurringOptions()">
                                    <option value="none">One-time Goal</option>
                                    <option value="weekly">Weekly Goal</option>
                                    <option value="biweekly">Every 2 Weeks</option>
                                    <option value="monthly">Monthly Goal</option>
                                </select>
                            </div>
                            
                            <div id="dateFields">
                                <div id="singleDateField">
                                    <label for="end_date" class="block text-sm font-medium text-gray-700 mb-1">Target Date</label>
                                    <input type="date" 
                                           id="end_date" 
                                           name="end_date" 
                                           class="w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring-blue-500"
                                           value="{{ old('end_date') }}"
                                           min="{{ date('Y-m-d', strtotime('+1 day')) }}">
                                </div>
                                
                                <div id="recurringDateFields" class="hidden space-y-3">
                                    <div>
                                        <label for="start_date" class="block text-sm font-medium text-gray-700 mb-1">Start Date</label>
                                        <input type="date" 
                                               id="start_date" 
                                               name="start_date" 
                                               class="w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring-blue-500"
                                               value="{{ old('start_date', date('Y-m-d')) }}"
                                               min="{{ date('Y-m-d') }}">
                                    </div>
                                    <div>
                                        <label for="recurrence_count" class="block text-sm font-medium text-gray-700 mb-1">Number of Occurrences</label>
                                        <input type="number" 
                                               id="recurrence_count" 
                                               name="recurrence_count" 
                                               class="w-full border-gray-300 rounded-md shadow-sm focus:border-blue-500 focus:ring-blue-500"
                                               value="{{ old('recurrence_count', 4) }}"
                                               min="1"
                                               max="52">
                                        <p class="text-xs text-gray-500 mt-1">How many times should this goal repeat?</p>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="flex space-x-3">
                                <button type="submit" class="flex-1 bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md text-sm font-medium transition-colors">
                                    Schedule Goal
                                </button>
                                <a href="{{ route('goals.create') }}" class="flex-1 bg-gray-100 hover:bg-gray-200 text-gray-700 px-4 py-2 rounded-md text-sm font-medium text-center transition-colors">
                                    Advanced
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">

                <!-- Recent Goals -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6">
                        <div class="flex items-center justify-between mb-4">
                            <h3 class="text-lg font-semibold text-gray-900">Your Goals</h3>
                            <a href="{{ route('goals.index') }}" class="text-blue-500 hover:text-blue-600 text-sm font-medium">
                                View All
                            </a>
                        </div>
                        
                        @php
                            $recentGoals = Auth::user()->goals()->latest()->take(3)->get();
                        @endphp
                        
                        @if($recentGoals->count() > 0)
                            <div class="space-y-3">
                                @foreach($recentGoals as $goal)
                                    <div class="border border-gray-200 rounded-lg p-3">
                                        <div class="flex items-center justify-between">
                                            <div class="flex-1">
                                                <h4 class="font-medium text-gray-900 text-sm">{{ $goal->title }}</h4>
                                                <div class="flex items-center space-x-2 mt-1">
                                                    <span class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium
                                                        @if($goal->status === 'active') bg-green-100 text-green-800
                                                        @elseif($goal->status === 'completed') bg-blue-100 text-blue-800
                                                        @else bg-gray-100 text-gray-800 @endif">
                                                        {{ ucfirst($goal->status) }}
                                                    </span>
                                                    <span class="text-xs text-gray-500">
                                                        Due: {{ $goal->end_date->format('M j, Y') }}
                                                    </span>
                                                </div>
                                            </div>
                                            @if($goal->status === 'active')
                                                <form action="{{ route('goals.complete', $goal) }}" method="POST" class="ml-2">
                                                    @csrf
                                                    @method('PATCH')
                                                    <button type="submit" 
                                                            class="text-green-600 hover:text-green-700 text-xs font-medium"
                                                            onclick="return confirm('Mark this goal as complete?')">
                                                        Complete
                                                    </button>
                                                </form>
                                            @endif
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        @else
                            <div class="text-center py-6">
                                <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"/>
                                </svg>
                                <h3 class="mt-2 text-sm font-medium text-gray-900">No goals yet</h3>
                                <p class="mt-1 text-sm text-gray-500">Get started by creating your first goal!</p>
                            </div>
                        @endif
                    </div>
                </div>
            </div>

            <!-- Quick Actions -->
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6">
                    <h3 class="text-lg font-semibold mb-4 text-gray-900">Quick Actions</h3>
                    <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
                        <a href="{{ route('goals.index') }}" class="flex items-center p-3 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
                            <svg class="w-6 h-6 text-blue-500 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"/>
                            </svg>
                            <div>
                                <div class="font-medium text-gray-900">View All Goals</div>
                                <div class="text-sm text-gray-500">Manage your goals</div>
                            </div>
                        </a>
                        
                        <a href="{{ route('goals.create') }}" class="flex items-center p-3 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
                            <svg class="w-6 h-6 text-green-500 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
                            </svg>
                            <div>
                                <div class="font-medium text-gray-900">Create Goal</div>
                                <div class="text-sm text-gray-500">Set a new target</div>
                            </div>
                        </a>
                        
                        <button onclick="showSmartGoalsVideo()" class="flex items-center p-3 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors text-left">
                            <svg class="w-6 h-6 text-purple-500 mr-3" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z"/>
                            </svg>
                            <div>
                                <div class="font-medium text-gray-900">SMART Goals</div>
                                <div class="text-sm text-gray-500">Learn the framework</div>
                            </div>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- SMART Goals Video Modal -->
    <div id="videoModal" class="fixed inset-0 bg-gray-600 bg-opacity-50 hidden z-50">
        <div class="flex items-center justify-center min-h-screen p-4">
            <div class="bg-white rounded-lg max-w-4xl w-full max-h-[90vh] overflow-hidden">
                <div class="flex items-center justify-between p-4 border-b">
                    <h3 class="text-lg font-semibold">How to Set SMART Goals</h3>
                    <button onclick="closeVideoModal()" class="text-gray-400 hover:text-gray-600">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
                        </svg>
                    </button>
                </div>
                <div class="p-4">
                    <div class="aspect-video bg-gray-100 rounded-lg flex items-center justify-center">
                        <iframe id="smartGoalsVideo" 
                                width="100%" 
                                height="100%" 
                                src="" 
                                frameborder="0" 
                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                                allowfullscreen
                                class="rounded-lg">
                        </iframe>
                    </div>
                    <div class="mt-4 text-sm text-gray-600">
                        <p><strong>SMART Goals Framework:</strong></p>
                        <ul class="list-disc list-inside mt-2 space-y-1">
                            <li><strong>Specific:</strong> Clear and well-defined</li>
                            <li><strong>Measurable:</strong> Quantifiable progress</li>
                            <li><strong>Achievable:</strong> Realistic and attainable</li>
                            <li><strong>Relevant:</strong> Meaningful to you</li>
                            <li><strong>Time-bound:</strong> Has a deadline</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Calendar functionality
        let currentDate = new Date();
        let currentMonth = currentDate.getMonth();
        let currentYear = currentDate.getFullYear();
        
        // Goals data for calendar
        @php
            $currentMonthGoals = Auth::user()->goals()
                ->whereMonth('end_date', date('m'))
                ->whereYear('end_date', date('Y'))
                ->get()
                ->map(function($goal) {
                    return [
                        'id' => $goal->id,
                        'title' => $goal->title,
                        'date' => $goal->end_date->format('Y-m-d'),
                        'status' => $goal->status,
                        'is_recurring' => $goal->is_recurring ?? false,
                        'recurrence_display' => $goal->recurrence_display ?? 'One-time'
                    ];
                });
        @endphp
        const goals = @json($currentMonthGoals);
        
        function generateCalendar(month, year) {
            const monthNames = [
                "January", "February", "March", "April", "May", "June",
                "July", "August", "September", "October", "November", "December"
            ];
            
            const daysInMonth = new Date(year, month + 1, 0).getDate();
            const firstDay = new Date(year, month, 1).getDay();
            
            let calendarHTML = `
                <div class="text-center mb-4">
                    <h4 class="text-lg font-semibold text-gray-900">${monthNames[month]} ${year}</h4>
                </div>
                <div class="grid grid-cols-7 gap-1 mb-2">
                    <div class="text-center text-xs font-medium text-gray-500 py-2">Sun</div>
                    <div class="text-center text-xs font-medium text-gray-500 py-2">Mon</div>
                    <div class="text-center text-xs font-medium text-gray-500 py-2">Tue</div>
                    <div class="text-center text-xs font-medium text-gray-500 py-2">Wed</div>
                    <div class="text-center text-xs font-medium text-gray-500 py-2">Thu</div>
                    <div class="text-center text-xs font-medium text-gray-500 py-2">Fri</div>
                    <div class="text-center text-xs font-medium text-gray-500 py-2">Sat</div>
                </div>
                <div class="grid grid-cols-7 gap-1">
            `;
            
            // Empty cells for days before the first day of the month
            for (let i = 0; i < firstDay; i++) {
                calendarHTML += '<div class="h-20 border border-gray-200 bg-gray-50"></div>';
            }
            
            // Days of the month
            for (let day = 1; day <= daysInMonth; day++) {
                const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
                const dayGoals = goals.filter(goal => goal.date === dateStr);
                const isToday = dateStr === new Date().toISOString().split('T')[0];
                
                let dayClass = 'h-20 border border-gray-200 bg-white p-1 cursor-pointer hover:bg-gray-50';
                if (isToday) {
                    dayClass += ' ring-2 ring-blue-500';
                }
                
                calendarHTML += `
                    <div class="${dayClass}" onclick="selectDate('${dateStr}')">
                        <div class="text-sm font-medium text-gray-900">${day}</div>
                        <div class="mt-1 space-y-1">
                `;
                
                dayGoals.forEach(goal => {
                    const statusColor = goal.status === 'completed' ? 'bg-green-100 text-green-800' : 
                                       goal.status === 'active' ? 'bg-blue-100 text-blue-800' : 'bg-gray-100 text-gray-800';
                    calendarHTML += `
                        <div class="text-xs px-1 py-0.5 rounded ${statusColor} truncate" title="${goal.title}">
                            ${goal.title.substring(0, 15)}${goal.title.length > 15 ? '...' : ''}
                            ${goal.is_recurring ? ' 🔄' : ''}
                        </div>
                    `;
                });
                
                calendarHTML += '</div></div>';
            }
            
            calendarHTML += '</div>';
            document.getElementById('calendar').innerHTML = calendarHTML;
        }
        
        function previousMonth() {
            currentMonth--;
            if (currentMonth < 0) {
                currentMonth = 11;
                currentYear--;
            }
            generateCalendar(currentMonth, currentYear);
        }
        
        function nextMonth() {
            currentMonth++;
            if (currentMonth > 11) {
                currentMonth = 0;
                currentYear++;
            }
            generateCalendar(currentMonth, currentYear);
        }
        
        function selectDate(dateStr) {
            document.getElementById('end_date').value = dateStr;
            document.getElementById('start_date').value = dateStr;
        }
        
        function toggleRecurringOptions() {
            const recurrenceType = document.getElementById('recurrence_type').value;
            const singleDateField = document.getElementById('singleDateField');
            const recurringDateFields = document.getElementById('recurringDateFields');
            
            if (recurrenceType === 'none') {
                singleDateField.classList.remove('hidden');
                recurringDateFields.classList.add('hidden');
                document.getElementById('end_date').required = true;
                document.getElementById('start_date').required = false;
            } else {
                singleDateField.classList.add('hidden');
                recurringDateFields.classList.remove('hidden');
                document.getElementById('end_date').required = false;
                document.getElementById('start_date').required = true;
            }
        }
        
        // Video modal functions
        function showSmartGoalsVideo() {
            const modal = document.getElementById('videoModal');
            const iframe = document.getElementById('smartGoalsVideo');
            
            iframe.src = 'https://www.youtube.com/embed/1-SvuFIQjK8';
            modal.classList.remove('hidden');
        }
        
        function closeVideoModal() {
            const modal = document.getElementById('videoModal');
            const iframe = document.getElementById('smartGoalsVideo');
            
            modal.classList.add('hidden');
            iframe.src = '';
        }
        
        // Initialize calendar on page load
        document.addEventListener('DOMContentLoaded', function() {
            generateCalendar(currentMonth, currentYear);
        });
        
        // Modal event listeners
        document.getElementById('videoModal').addEventListener('click', function(e) {
            if (e.target === this) {
                closeVideoModal();
            }
        });
        
        document.addEventListener('keydown', function(e) {
            if (e.key === 'Escape') {
                closeVideoModal();
            }
        });
    </script>
</x-app-layout>
